### ISSUE TITLE
Create a command line interface for gasper

### ISSUE THREAD

**Issue by supra08** [sdslabs/gasper#211]
Currently we have the REST API provided by the master service to interact with Gasper. A CLI tool `gctl` would be an addon functionality that would directly interact with the API and enhance its functionality. 
The CLI tool will be second class citizen in the gasper ecosystem. That is, we will first need to generate a PA Token from the UI/Rest API and use that token to authorize `gctl`.
A config will be maintained for the project in `yaml` file. The ctl would parse the config and perform the requests.
A minimal metrics and logs visualization would also be presented by `gctl`.

**Comment by mhk19** [comment]
Done https://github.com/sdslabs/gctl
