### ISSUE TITLE
Re-register the user

### ISSUE THREAD

**Issue by mhk19** [sdslabs/gasper#221]
[https://github.com/sdslabs/gasper/blob/develop/services/master/controllers/user.go](url)
In the register function, the code checks if the email id is already registered or not. But when we delete a user, it is just marked as (deleted: true), not removed from the database. The register function should either mark deleted as false or create a new user with the email id.

**Comment by supra08** [comment]
It's an intended flow. We cannot let users to re-register themselves if their account has been deleted by the admin.
